### ISSUE TITLE
Scheduled job matcher fails with mismatching timezones

### ISSUE THREAD

**Issue by nbibler** [wspurgin/rspec-sidekiq#124]
The internal implementation of the `at` and `on` matchers rely on converting Time instances to strings. However, prior to converting to strings, they don't normalize on a timezone (like UTC). So, the string comparison fails if the timezones for the two instances mismatch, even while the time itself is identical.

The matcher incorrectly fails because it believes these two "times" don't match:

```
"2017-05-02 18:26:52 +0000" != "2017-05-02 14:26:52 -0400"
```

**Comment by tom-williams** [comment]
Also a problem with testing perform_in over a sommer/normal time shift:

So RSpec::Sidekiq::Mathers::JobOptionsParser method `def in_evaluator(value)`

Should probably be written (to also allow for possible concurrency issue):
```
def in_evaluator(value)
  return false if job['at'].blank?
  in_value = Time.now.to_f + value.to_f
  at_value = Time.at(job['at']).to_f
  return (at_value + 2) > in_value && in_value > (at_value - 2)
end
```
To allow for a slow running test having a difference between enqueue call to Time.now and the in_evaluator's call to Time.now (maybe 2 seconds is too much)

**Comment by wspurgin** [comment]
A long time later but....

IMHO Doing any expectations around use of Time should involve freezing time. Sidekiq calculates the `"at"` context using `Time.now`, so there's gonna be natural differences when we evaluate it in the matcher if Time isn't frozen first. If testing the time (via `at` or `in`) is an important test for your use-case, I strongly recommend using [`travel_to`](https://devdocs.io/rails~7.0/activesupport/testing/timehelpers#method-i-travel_to) from `ActiveSupport` or any other common time freezing function.
