### ISSUE TITLE
Check if a job is scheduled for right now

### ISSUE THREAD

**Issue by dpoetzsch** [wspurgin/rspec-sidekiq#143]
I'd expect the following to work (I am already wrapping this in timecop):

```ruby
Timecop.freeze do
  Awesomejob.perform_in 0.seconds 'Awesome', true
  # test with...
  expect(AwesomeJob).to have_enqueued_sidekiq_job('Awesome', true).in(0.seconds)
end
```

Well, it does not work leaving me with no way to check if the job was enqueued for now and not for a later time.

I already checked your code and I think the problem is that you directly return false if the sidekiq job is scheduled at `nil`, but I think `nil` should instead be treated as `Time.now`. If you're interested I can open a PR for this.

**Comment by mathieujobin** [comment]
Expect first

**Comment by mathieujobin** [comment]
Actually. I am not sure. I have no idea. Sorry.

**Comment by wspurgin** [comment]
Late to the party but I think the matcher you're looking for is `at` e.g.,
```ruby
Timecop.freeze do
  AwesomeJob.perform_in 0.seconds 'Awesome', true
  # test with...
  expect(AwesomeJob).to have_enqueued_sidekiq_job('Awesome', true).at(Time.now)
end
```

I'm sure `AwesomeJob.perform_in 0.seconds` is contrived for this example... but just calling out that, if one wants something enqueued immediately, one should use `perform_async` not `peform_in` with a 0 length interval.
