### ISSUE TITLE
have_enqueued_sidekiq_job Diff is Wrong

### ISSUE THREAD

**Issue by sshaw** [wspurgin/rspec-sidekiq#162]
```rb
expect(Sidekiq::Worker).to have_enqueued_sidekiq_job('Foo', 'BarX')
```

Will fail with 
```
     expected to have an enqueued Sidekiq::Worker job
         arguments: ["Foo", "BarX"]
     found
         arguments: [["Foo", "Bar"]]
```

Note that it presents an `Array` and an `Array` of `Array`s.

**Comment by cgunther** [comment]
I believe this is correct. The "expected arguments" is showing you the arguments from your assertion in array form. The "found arguments" is showing you the arguments of all the jobs that are enqueued. The length of the outermost array is essentially the number of jobs enqueued. If you had multiple jobs enqueued the message would look like:
```
     expected to have an enqueued Sidekiq::Worker job
         arguments: ["Foo", "BarX"]
     found
         arguments: [["Foo", "Bar"], ["Foo", "Bar2"]]
```

**Comment by Tolsee** [comment]
+1

I encountered this when using `Sidekiq::Client.enqueue_to_in`.

**Comment by michaelfranzl** [comment]
I have the same issue as @Tolsee . If I am passing an array as one of the arguments, that array is displayed flattened in the diff message:

```
expected to have an enqueued MyJob job
  arguments: ["abc", [1, 2], 3]
found
  arguments: [["abc", 1, 2, 3]]
```

**Comment by stefanzero** [comment]
I had a similar problem, where the actual arguments were in a nested array.  Upon careful inspection, I saw that I set one of the expected items incorrectly.  After I fixed that argument, the test passed and it no longer displayed the nested array.
