### ISSUE TITLE
Checking for time has a different format expectation 

### ISSUE THREAD

**Issue by MaicolBen** [wspurgin/rspec-sidekiq#167]
Since we upgraded to 3.1.0, this match `have_enqueued_sidekiq_job(id).in(20.minutes)` fails randomly only in the CI:
```
       expected to have an enqueued MyWorker job 
         arguments: [1] 
         options: {"in"=>20 minutes}
 
       found 
         arguments: [[1]] 
         options: [{"at"=>1593448009.99905}]
 ```

That seems weird since in that code we don't have `at`

**Comment by wspurgin** [comment]
It sure does. I updated this in #194 - you'll now see `"at"` and `"at"` with the EPOCH second format
