### ISSUE TITLE
Disable all sidekiq jobs for testing

### ISSUE THREAD

**Issue by mrothenbuhler** [wspurgin/rspec-sidekiq#169]
Hi--is there a way to do this? We have some auto-run jobs we'd like to disable

**Comment by wspurgin** [comment]
If by "disable" you mean that you don't want any Sidekiq Jobs to run "for real", I think you're looking for `Sidekiq::Testing.fake!` which is part of Sidekiq's builtin testing framework (this framework includes it for you, and `fake!` is the default mode). https://github.com/sidekiq/sidekiq/wiki/testing
