### ISSUE TITLE
Block syntax `enqueue_sidekiq_job` matcher

### ISSUE THREAD

**Issue by pirj** [wspurgin/rspec-sidekiq#170]
There is a slight problem with the existing `have_enqueued_sidekiq_job` matcher, specifically that it's prone to the [incidental state error](https://rspec.rubystyle.guide/#incidental-state), unlike `rspec-rails`'s [Active Job-oriented `have_enqueued_job`](https://relishapp.com/rspec/rspec-rails/v/4-0/docs/job-specs/job-spec) that is a block syntax matcher. E.g.:
```ruby
class Model < ActiveRecord::Base
  after_save :schedule_job

  def foo!
    # I do nothing!
  end

  private

  def schedule_job
    AwesomeJob.perform_async('hello')
  end
end
```

```ruby
RSpec.describe Model do
  describe '#foo!' do
    subject!(:model) { Model.create! }

    it 'schedules AwesomeJob' do
      model.foo!
      expect(AwesomeJob).to have_enqueued_sidekiq_job('hello')
    end
  end
end
```

In the above example, the job was scheduled. But it would be scheduled no matter if `model.foo!` was called or not.

I suggest adding a block-syntax `enqueue_sidekiq_job` matcher that would work similarly to `rspec-rails`'s one:

```ruby
RSpec.describe Model do
  describe '#foo!' do
    subject!(:model) { Model.create! }

    it 'schedules AwesomeJob' do
      expect { model.foo! }
        .to enqueue_sidekiq_job(AwesomeJob).with('hello')
    end
  end
end
```

I can handle adding it if you have no objections on the idea.

**Comment by pirj** [comment]
Ping

**Comment by sineed** [comment]
hey @pirj have you worked on this one? I like the idea and I'm curious if I can sneak the implementation :)

**Comment by pirj** [comment]
I haven't yet, but since you support the idea, I'll tackle it.
For the implementation, I think of something very similar to [this](https://github.com/rspec/rspec-rails/blob/a78519850c8c8c3cf86319b2cc0b214bf16a6372/lib/rspec/rails/matchers/active_job.rb#L233).

**Comment by sineed** [comment]
Yes, good to add negated matcher as well. It will be quite handy and readable to see something like:

```ruby
expect { subject }
  .to have_enqueued_sidekiq_job(FooJob)
  .and have_enqueued_sidekiq_job(BarJob)
  .and avoid_enqueuing_sidekiq_job(BazJob)
```

**Comment by pirj** [comment]
Released as https://github.com/pirj/rspec-enqueue_sidekiq_job https://rubygems.org/gems/rspec-enqueue_sidekiq_job

I've closed the PR. Please feel free to close the ticket as well.

**Comment by wspurgin** [comment]
I'd like this in `rspec-sidekiq` and I've added it as a goal for v4. If you're still interested @pirj (I know it's been several years), feel free to re-open a PR. Otherwise I'll try and add a block syntax version using the same style `expect { }.to enqueue_sidekiq_job(...)`

**Comment by pirj** [comment]
I ended up creating https://github.com/pirj/rspec-enqueue_sidekiq_job
Since we don’t use Sidekiq directly in my current project, I’m not so interested in actively maintaining the repo further. I’ll be happy if you take it over, borrow its code, or just include the gem as a runtime dependency, whatever you feel is right.

And thanks for the gem!

**Comment by wspurgin** [comment]
Thanks @pirj 👍 Appreciate it.
