### ISSUE TITLE
Issue with yaml safe loading (psych gem)

### ISSUE THREAD

**Issue by Paul-Yves** [wspurgin/rspec-sidekiq#177]
I am trying to upgrade to psych 4 but there are breaking changes on yaml loading and all my expect().to be_delayed breaks.

There are some examples of other library starting to use safe load.

> See for example #503 where the library adapted to the changes: sparklemotion/http-cookie#34.

Is it something rspec-sidekiq would consider do ?

**Comment by Paul-Yves** [comment]
The gem I used no longer has dependency to reek so I no longer have the issue, however I guess that the issue remains for those who upgrade psych version.

**Comment by wspurgin** [comment]
Thank you for the issue! Many years late but I think this will be fixed in V4 with https://github.com/wspurgin/rspec-sidekiq/commit/8fc3f9dca869eb746c88902afe72f2255108524d#diff-8198780b626ed0023b2808c305db028adadd80c82bb05a64f600a3f47b93f1b0R61-R66
