### ISSUE TITLE
Using ActiveJob::Base with sidekiq_options raises an error 

### ISSUE THREAD

**Issue by gnumarcelo** [wspurgin/rspec-sidekiq#181]
I'm using Sidekiq with ActiveJob on Rails 6.0.4, and I have defined the following class:

```ruby
class SampleJob < ApplicationJob
  self.queue_adapter = :sidekiq

  sidekiq_options queue: :critical, retry: 19

  def perform(text)
    puts "Something #{text}"
  end
end
```
It works as expected when I run the code in development mode, but my specs fails with:
```ruby
An error occurred while loading ./spec/jobs/sample_job_spec.rb.
Failure/Error: sidekiq_options queue: :critical, retry: 19

NoMethodError:
  undefined method `sidekiq_options' for SampleJob:Class
```

I've identified this fails because in test environment I am using `rspec-sidekiq`. Does anyone have experienced the same issue? Is `rspec-sidekiq` somehow incompatible with the code above?

Thanks!

**Comment by sehgalmayank001** [comment]
@gnumarcelo , were you able to resolve this? I am facing the same issue.

`sidekiq_options` somehow aren't defined for rspec but are available in rails console for test env.
```Ruby
Failure/Error: sidekiq_options queue: :custom_job_queue
     
 NoMethodError:
   undefined method `sidekiq_options' for CustomJobWorker:Class
```

**Comment by gnumarcelo** [comment]
@sehgalmayank001 In the end, we've decided to go with `Sidekiq::Job` instead of `ActiveJob `.

**Comment by jcksnparsons** [comment]
Hey, just going to add to this just in case you're still wondering:

We got around this by including `Sidekiq::Job::Options` on our job. That got our tests passing as expected.

```ruby
class SampleJob < ApplicationJob
  include Sidekiq::Job::Options

  self.queue_adapter = :sidekiq

  sidekiq_options queue: :critical, retry: 19

  def perform(text)
    puts "Something #{text}"
  end
end
```

**Comment by wspurgin** [comment]
Hmmm curious! I'll dig into this more. I would've definitely thought `sidekiq_options` to have been available on Active Job as of Sidekiq 6 (at least according to the [changelog](https://github.com/sidekiq/sidekiq/blob/b3225cef44d93d2ce98c5d74ac582bf31066095d/docs/6.0-Upgrade.md?plain=1#L10-L13)). For anyone still actively using ActiveJob with Sidekiq 6, any chance you recall _what_ the led you to `rspec-sidekiq` as being the culprit?

**Comment by wspurgin** [comment]
From what I can tell, Sidekiq does this with a Rails initializer: https://github.com/sidekiq/sidekiq/blob/b3225cef44d93d2ce98c5d74ac582bf31066095d/lib/sidekiq/rails.rb#L34

I put together a vanilla install of Rails that uses rspec-sidekiq and ActiveJob and I can't reproduce:
Active Job class with `sidekiq_options`
https://github.com/wspurgin/vanilla/blob/sidekiq/rspec-sidekiq/activejob/app/jobs/application_job.rb

Spec:
https://github.com/wspurgin/vanilla/blob/sidekiq/rspec-sidekiq/activejob/spec/jobs/application_job_spec.rb
