### ISSUE TITLE
How to expect to have_enqueued_sidekiq_job with specific queue?  - [setting queue name at runtime]

### ISSUE THREAD

**Issue by RichardsonWTR** [wspurgin/rspec-sidekiq#184]
My class decides the queue name dynamically depending on business rules. 

How to expect that my class has enqueued the specific job with the specific arguments in the specific queue?

One way to to this could be with this API
```ruby
expect(AwesomeJob).to have_enqueued_sidekiq_job('Awesome', true).at(time).on('my_queue')
```

### Why ?
Because my code is enqueuing the job in a command like this one: 
```ruby
AwesomeJob.set(queue: queue_name).perform_async('Awesome', true)
```

### One way to accomplish this

One way that I've found to accomplish this is (But I don't think its elegant): 
```ruby
expect(AwesomeJob.jobs.last['queue']).to eq 'my_queue'
```

**Comment by wspurgin** [comment]
Heyo 👋 This repo was in a bit of limbo for the last year or two. I think this is a nice feature to add. I like the `on` syntax. Someone made an attempt a few years back in #164 with `to` but it needs revisiting. I'll look into add this to the v4 milestone
