### ISSUE TITLE
NameError: uninitialized constant RSpec::Matchers::Composable

### ISSUE THREAD

**Issue by mamirad** [wspurgin/rspec-sidekiq#212]
rails aborted!
NameError: uninitialized constant RSpec::Matchers::Composable

        include RSpec::Matchers::Composable
                               ^^^^^^^^^^^^
Did you mean?  Comparable
/home/amir/.rvm/gems/ruby-3.1.4@IWM/gems/rspec-sidekiq-4.1.0/lib/rspec/sidekiq/matchers/base.rb:165:in `<class:Base>'
/home/amir/.rvm/gems/ruby-3.1.4@IWM/gems/rspec-sidekiq-4.1.0/lib/rspec/sidekiq/matchers/base.rb:163:in `<module:Matchers>'
/home/amir/.rvm/gems/ruby-3.1.4@IWM/gems/rspec-sidekiq-4.1.0/lib/rspec/sidekiq/matchers/base.rb:3:in `<module:Sidekiq>'
/home/amir/.rvm/gems/ruby-3.1.4@IWM/gems/rspec-sidekiq-4.1.0/lib/rspec/sidekiq/matchers/base.rb:2:in `<module:RSpec>'
/home/amir/.rvm/gems/ruby-3.1.4@IWM/gems/rspec-sidekiq-4.1.0/lib/rspec/sidekiq/matchers/base.rb:1:in `<main>'

**Comment by wspurgin** [comment]
Hi @mamirad, I'll need a little more to go on than this stacktrace. Can you provide a reproduceable example (e.g., Gemfile and example spec)?

**Comment by wspurgin** [comment]
Just a guess, but do you have `rspec-sidekiq` in the same group (presumably `:test`) as `rspec` in your Gemfile?

**Comment by lime666** [comment]
This answer helps me with the same issue: https://stackoverflow.com/questions/27834963/uninitialized-constant-rspecmatcherscomposable
