### ISSUE TITLE
Remove have_enqueued_jobs matcher

### ISSUE THREAD

**Issue by philostler** [wspurgin/rspec-sidekiq#37]
Matcher is pointless given that you can do...

``` ruby
expect(AwesomeJob).to have(1).jobs
# or
expect(AwesomeJob).to have(1).enqueued.jobs
```

Remove, or ideally keep with a message telling people to use the other syntax

**Comment by ingolfured** [comment]
`have` doesn't work anymore for Rspec 3.2, what do you recommend using instead?

**Comment by ingolfured** [comment]
Never mind, I just used
```
expect(DaWorker.jobs.size).to eq(5)
```
